---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  ansible-lint
platforms:
  - name: instance
    image: "thetarto/ansible-${MOLECULE_DISTRIB}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: testinfra
  lint:
    name: flake8
